### ISSUE TITLE
JWT iframe request returns TypeError

### ISSUE THREAD

**Issue by afaraha8403** [deso-protocol/identity#114]
When sending the below postMessage an error is returned.  Probably hit this snap on the JWT request as I was building the internal service...

_TypeError: Cannot destructure property 'service' of 't' as it is undefined._

**Request**
```
  let jwtReq = {
    id: 'XXXX,
    service: 'identity',
    method: 'jwt',
    payload: {
      accessLevel: user.accessLevel,
      accessLevelHmac: user.accessLevelHmac,
      encryptedSeedHex: user.encryptedSeedHex
    }
  };
  vLog('JWT request', jwtReq);
  let iFrame = document.getElementById('SOMEID').firstChild.contentWindow;
  iFrame.postMessage(jwtReq, '*');
```

**Returned Error**
```
main-es2015.7fd4f7fb2e638fd391c6.js:1 ERROR TypeError: Cannot destructure property 'service' of 't' as it is undefined.
    at e.handleMessage (main-es2015.7fd4f7fb2e638fd391c6.js:1:1661185)
    at main-es2015.7fd4f7fb2e638fd391c6.js:1:1657249
    at u.invokeTask (polyfills-es2015.f888aaa0bd730994945c.js:1:20709)
    at Object.onInvokeTask (main-es2015.7fd4f7fb2e638fd391c6.js:1:1417062)
    at u.invokeTask (polyfills-es2015.f888aaa0bd730994945c.js:1:20630)
    at a.runTask (polyfills-es2015.f888aaa0bd730994945c.js:1:16118)
    at l.invokeTask [as invoke] (polyfills-es2015.f888aaa0bd730994945c.js:1:21759)
    at f (polyfills-es2015.f888aaa0bd730994945c.js:1:33720)
    at h (polyfills-es2015.f888aaa0bd730994945c.js:1:33965)
```

Traces back to this 

```
                handleMessage(e) {
                    const {data: t} = e
                      , {service: r, method: n} = t;
                    "identity" === r && (n ? this.handleRequest(e) : this.handleResponse(e))
                }
```

**Comment by maebeam** [comment]
Wrap in data key

```
  iFrame.postMessage({data: jwtReq}, '*');
```

**Comment by afaraha8403** [comment]
@maebeam this does not solve the issue.  Now identity does not return anything!
